### ISSUE TITLE
Hard Coded options

### ISSUE THREAD

**Issue by nosizejosh** [JutoApp/meteor-autoform-telephone-input#2] opened 2019-07-27 19:39 UTC
Hello There,

I have been trying to figure out how to make your package more flexible and able to accept all the options of the [original](https://github.com/jackocnr/intl-tel-input) npm package.
I think this part is where the hard-code happens.

```
Template["intlTelephoneInput"].onRendered(function(){
  const tmpl = Template.instance();
  let input = tmpl.$("input[type=tel]")[0];
  this.iti.set(intlTelInput(input, {
    preferredCountries: ["us","au","gb"],
    utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/15.0.2/js/utils.js"
  }));
});
```

Is there a way you can make the package more flexible or point me to how to rework this to be able to accept the options allowed by original app?

I am looking to be able to do

```
phone: {
    type: String,
    autoform: {
      type: 'intl-tel-input',
      'class': 'form-control',
      afFieldInput: {
        inputOptions: {
          autoFormat: true,
          separateDialCode: true,
          preferredCountries: ["gh","za","gb"],
          initialCountry: 'gh',
          autocomplete: "tel"
        }
      }
    }
  },
```

**Comment by cunneen** [comment] 2019-07-28 15:57
Hi, this is a duplicate of #1. You can use the API in the template's callbacks.

**Comment by nosizejosh** [comment] 2019-07-28 20:54
@cunneen Thanks for the reply.  I tried and was able to implement  setCountry as above, but still having issues with other options. for instance trying to set preferred countries as follows
imported ```const intlTelInput = require('intl-tel-input'); ```  into my template  and in the onrendered doing the following;
```
let itiElemJQ = this.$(".intl-tel-input input");
    // if (itiElemJQ.val() === "") { // set the initial country if there's no value already
    let itiElement = itiElemJQ[0];
    let iti = window.intlTelInputGlobals.getInstance(itiElement);
    iti.setCountry("gh");
    iti.set(intlTelInput(itiElemJQ, {
        preferredCountries: ["us","au","gb"]
    }));
// }
```

results in the following error.  

```
TypeError: input.getAttribute is not a function
    at new Iti (modules.js?hash=6844c39b1f8502b7463b2f184b0dd77576cf24dd:46881)
    at modules.js?hash=6844c39b1f8502b7463b2f184b0dd77576cf24dd:48017
    at Blaze.TemplateInstance.aboutEventFormPartialOnCreated (aboutEventFormPartial.js:24)
    at blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3398
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3769)
    at fireCallbacks (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3394)
    at Blaze.View.<anonymous> (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:3487)
    at blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1845
    at Object.Blaze._withCurrentView (blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:2271)
    at blaze.js?hash=51f4a3bdae106610ee48d8eff291f3628713d847:1844
```

please how does one set the rest of the options from a template?

**Comment by cunneen** [comment] 2019-07-28 23:50
~~You haven't defined `intlTelInput` in your code, that's why it's giving you an error.~~

For use of the API, please refer to the [intl-tel-input](https://github.com/jackocnr/intl-tel-input#public-methods) package. The API does not provide a way of setting `preferredCountries`. I'll reopen this ticket.

**Comment by nosizejosh** [comment] 2019-07-29 00:58
@cunneen  I actually imported it 
The API has the [intel-input](https://github.com/jackocnr/intl-tel-input#options) which i am trying to set using your package.

from your code and the snippet below, you were able to set prefferedCountries but in a way that's hard coded and inside the package itself

```
Template["intlTelephoneInput"].onRendered(function(){
  const tmpl = Template.instance();
  let input = tmpl.$("input[type=tel]")[0];
  this.iti.set(intlTelInput(input, {
    preferredCountries: ["us","au","gb"],
    utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/15.0.2/js/utils.js"
  }));
}); 
```
below is a similar snippet from [harryadel ](https://github.com/harryadel/autoform-intl-tel-input/blob/master/autoform-intl-tel-input.js)which achieves almost the same thing but with that i am unable to perform validation.

```
Template.afIntlTelInput.rendered = function () {
  var $input = this.$('input');
  var data = this.data;

  // instanciate intlTelInput
  $input.intlTelInput(data.atts.inputOptions);

  // set and reactively update values
  this.autorun(function () {
    var data = Template.currentData();

    // set field value
    if (typeof data.value !== 'undefined') {
      $input.val(data.value);
    }
  });

};
```
I have been trying to figure out a way to make your code accept options just like this package does with the snippet about and that will make your version perfect for my case and also most flexible to use.

**Comment by cunneen** [comment] 2019-07-29 01:00
Oh cool thanks for pointing me to @harryadel's package. I'll look into it.

**Comment by cunneen** [comment] 2019-07-29 01:43
OK try updating your package to v1.0.2. It takes a new attribute in the schema :

```
        intlTelInputOptions: {
          preferredCountries: ["us","au","gb"],
          utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/15.0.2/js/utils.js"
        }
```

**Closed as completed by cunneen** 2019-07-29 01:43 UTC

**Comment by nosizejosh** [comment] 2019-07-29 02:23
nice work! setting a helper and passing options also works! thanks!!!
